<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Shouldly" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Foundry.Shared\Foundry.Shared.csproj" />
    <ProjectReference Include="..\..\src\Modules\Issues\Foundry.Modules.Issues.Contracts\Foundry.Modules.Issues.Contracts.csproj" />
    <ProjectReference Include="..\..\src\Modules\Monitoring\Foundry.Modules.Monitoring.Contracts\Foundry.Modules.Monitoring.Contracts.csproj" />
    <ProjectReference Include="..\..\src\Modules\Workers\Foundry.Modules.Workers\Foundry.Modules.Workers.csproj" />
    <ProjectReference Include="..\..\src\Modules\Workers\Foundry.Modules.Workers.Contracts\Foundry.Modules.Workers.Contracts.csproj" />
  </ItemGroup>

</Project>
