<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Shouldly" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Foundry.Testing\Foundry.Testing.csproj" />
    <ProjectReference Include="..\..\src\Foundry.Shared.Infrastructure.Docker\Foundry.Shared.Infrastructure.Docker.csproj" />
    <ProjectReference Include="..\..\src\Foundry.WebApi\Foundry.WebApi.csproj" />
    <ProjectReference Include="..\..\src\Modules\Monitoring\Foundry.Modules.Monitoring.Contracts\Foundry.Modules.Monitoring.Contracts.csproj" />
    <ProjectReference Include="..\..\src\Modules\Issues\Foundry.Modules.Issues.Contracts\Foundry.Modules.Issues.Contracts.csproj" />
    <ProjectReference Include="..\..\src\Modules\Workers\Foundry.Modules.Workers.Contracts\Foundry.Modules.Workers.Contracts.csproj" />
    <ProjectReference Include="..\..\src\Modules\Monitoring\Foundry.Modules.Monitoring\Foundry.Modules.Monitoring.csproj" />
    <ProjectReference Include="..\..\src\Modules\Issues\Foundry.Modules.Issues\Foundry.Modules.Issues.csproj" />
    <ProjectReference Include="..\..\src\Modules\Workers\Foundry.Modules.Workers\Foundry.Modules.Workers.csproj" />
    <ProjectReference Include="..\..\src\Modules\Settings\Foundry.Modules.Settings\Foundry.Modules.Settings.csproj" />
    <ProjectReference Include="..\..\src\Modules\Settings\Foundry.Modules.Settings.Contracts\Foundry.Modules.Settings.Contracts.csproj" />
  </ItemGroup>

</Project>
