<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="Docker.DotNet" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Foundry.ServiceDefaults\Foundry.ServiceDefaults.csproj" />
    <ProjectReference Include="..\Foundry.Shared.Infrastructure\Foundry.Shared.Infrastructure.csproj" />
    <ProjectReference Include="..\Foundry.Shared\Foundry.Shared.csproj" />
    <ProjectReference Include="..\Modules\Issues\Foundry.Modules.Issues\Foundry.Modules.Issues.csproj" />
    <ProjectReference Include="..\Modules\Monitoring\Foundry.Modules.Monitoring\Foundry.Modules.Monitoring.csproj" />
  </ItemGroup>

</Project>
