<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Foundry.Modules.Credentials.Contracts\Foundry.Modules.Credentials.Contracts.csproj" />
    <ProjectReference Include="..\..\..\Foundry.Shared.Infrastructure\Foundry.Shared.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\Foundry.Shared.Infrastructure.Docker\Foundry.Shared.Infrastructure.Docker.csproj" />
    <ProjectReference Include="..\..\Workers\Foundry.Modules.Workers.Contracts\Foundry.Modules.Workers.Contracts.csproj" />
    <ProjectReference Include="..\..\Settings\Foundry.Modules.Settings\Foundry.Modules.Settings.csproj" />
  </ItemGroup>

</Project>
