// <auto-generated />
using System;
using Foundry.WebApi.Shared.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Foundry.WebApi.Migrations
{
    [DbContext(typeof(FoundryDbContext))]
    [Migration("20260528150224_AddWorkerRunsAndWorkerReports")]
    partial class AddWorkerRunsAndWorkerReports
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("Foundry.WebApi.Modules.Issues.Domain.Issue", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("author");

                    b.Property<string>("BlockedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2147483647)
                        .HasColumnType("TEXT")
                        .HasColumnName("blocked_by")
                        .HasDefaultValueSql("'[]'");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("DetectedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("detected_at");

                    b.Property<int>("IssueNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("issue_number");

                    b.Property<string>("Labels")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .HasColumnType("TEXT")
                        .HasColumnName("labels");

                    b.Property<Guid>("MonitoredRepositoryId")
                        .HasColumnType("TEXT")
                        .HasColumnName("monitored_repository_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("url");

                    b.Property<string>("state")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("state");

                    b.HasKey("Id");

                    b.HasIndex("MonitoredRepositoryId", "IssueNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_issues_monitored_repository_id_issue_number");

                    b.ToTable("issues", (string)null);

                    b.HasDiscriminator<string>("state").IsComplete(true).HasValue("Issue");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Foundry.WebApi.Modules.Monitoring.Domain.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("base_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("SecretKeyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("secret_key_name");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("accounts", (string)null);

                    b.HasDiscriminator<string>("type").IsComplete(true).HasValue("Account");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Foundry.WebApi.Modules.Monitoring.Domain.MonitoredRepository", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT")
                        .HasColumnName("account_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LastPolledAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_polled_at");

                    b.Property<TimeSpan?>("PollInterval")
                        .HasColumnType("TEXT")
                        .HasColumnName("poll_interval");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("slug");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_monitored_repositories_account_id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_monitored_repositories_slug");

                    b.ToTable("monitored_repositories", (string)null);
                });

            modelBuilder.Entity("Foundry.WebApi.Modules.Workers.Domain.WorkerReport", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("IngestedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("ingested_at");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("report_type");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sequence_number");

                    b.Property<Guid>("WorkerRunId")
                        .HasColumnType("TEXT")
                        .HasColumnName("worker_run_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkerRunId")
                        .HasDatabaseName("ix_worker_reports_worker_run_id");

                    b.ToTable("worker_reports", (string)null);
                });

            modelBuilder.Entity("Foundry.WebApi.Modules.Workers.Domain.WorkerRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<Guid>("IssueId")
                        .HasColumnType("TEXT")
                        .HasColumnName("issue_id");

                    b.Property<string>("state")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("state");

                    b.HasKey("Id");

                    b.ToTable("worker_runs", (string)null);

                    b.HasDiscriminator<string>("state").IsComplete(true).HasValue("WorkerRun");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Foundry.WebApi.Modules.Issues.Domain.BlockedIssue", b =>
                {
                    b.HasBaseType("Foundry.WebApi.Modules.Issues.Domain.Issue");

                    b.HasDiscriminator().HasValue("blocked");
                });

            modelBuilder.Entity("Foundry.WebApi.Modules.Issues.Domain.DetectedIssue", b =>
                {
                    b.HasBaseType("Foundry.WebApi.Modules.Issues.Domain.Issue");

                    b.HasDiscriminator().HasValue("detected");
                });

            modelBuilder.Entity("Foundry.WebApi.Modules.Issues.Domain.InProgressIssue", b =>
                {
                    b.HasBaseType("Foundry.WebApi.Modules.Issues.Domain.Issue");

                    b.Property<Guid>("WorkerRunId")
                        .HasColumnType("TEXT")
                        .HasColumnName("worker_run_id");

                    b.HasDiscriminator().HasValue("in_progress");
                });

            modelBuilder.Entity("Foundry.WebApi.Modules.Issues.Domain.QueuedIssue", b =>
                {
                    b.HasBaseType("Foundry.WebApi.Modules.Issues.Domain.Issue");

                    b.HasDiscriminator().HasValue("queued");
                });

            modelBuilder.Entity("Foundry.WebApi.Modules.Monitoring.Domain.GitHubAccount", b =>
                {
                    b.HasBaseType("Foundry.WebApi.Modules.Monitoring.Domain.Account");

                    b.HasDiscriminator().HasValue("github");
                });

            modelBuilder.Entity("Foundry.WebApi.Modules.Workers.Domain.ActiveRun", b =>
                {
                    b.HasBaseType("Foundry.WebApi.Modules.Workers.Domain.WorkerRun");

                    b.Property<string>("ContainerId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("container_id");

                    b.Property<string>("LatestProgress")
                        .HasMaxLength(2147483647)
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .HasColumnName("latest_progress");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at");

                    b.HasDiscriminator().HasValue("active");
                });

            modelBuilder.Entity("Foundry.WebApi.Modules.Workers.Domain.CompletedRun", b =>
                {
                    b.HasBaseType("Foundry.WebApi.Modules.Workers.Domain.WorkerRun");

                    b.Property<string>("BranchName")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("branch_name");

                    b.Property<DateTimeOffset>("CompletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("completed_at");

                    b.Property<int>("ExitCode")
                        .HasColumnType("INTEGER")
                        .HasColumnName("exit_code");

                    b.Property<string>("PullRequestUrl")
                        .HasMaxLength(2000)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("pull_request_url");

                    b.HasDiscriminator().HasValue("completed");
                });

            modelBuilder.Entity("Foundry.WebApi.Modules.Workers.Domain.FailedRun", b =>
                {
                    b.HasBaseType("Foundry.WebApi.Modules.Workers.Domain.WorkerRun");

                    b.Property<DateTimeOffset>("FailedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("failed_at");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .HasColumnType("TEXT")
                        .HasColumnName("reason");

                    b.HasDiscriminator().HasValue("failed");
                });

            modelBuilder.Entity("Foundry.WebApi.Modules.Workers.Domain.StartingRun", b =>
                {
                    b.HasBaseType("Foundry.WebApi.Modules.Workers.Domain.WorkerRun");

                    b.HasDiscriminator().HasValue("starting");
                });

            modelBuilder.Entity("Foundry.WebApi.Modules.Monitoring.Domain.MonitoredRepository", b =>
                {
                    b.HasOne("Foundry.WebApi.Modules.Monitoring.Domain.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
