// <auto-generated />
using System;
using Foundry.WebApi.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Foundry.WebApi.Migrations
{
    [DbContext(typeof(FoundryDbContext))]
    [Migration("20260610214527_AddGlobalSettings")]
    partial class AddGlobalSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("Foundry.Modules.Issues.Domain.Issue", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("author");

                    b.Property<string>("BlockedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2147483647)
                        .HasColumnType("TEXT")
                        .HasColumnName("blocked_by")
                        .HasDefaultValueSql("'[]'");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .HasColumnName("body");

                    b.Property<string>("DetectedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("detected_at");

                    b.Property<int>("IssueNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("issue_number");

                    b.Property<string>("Labels")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .HasColumnType("TEXT")
                        .HasColumnName("labels");

                    b.Property<Guid>("MonitoredRepositoryId")
                        .HasColumnType("TEXT")
                        .HasColumnName("monitored_repository_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("url");

                    b.Property<string>("state")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("state");

                    b.HasKey("Id");

                    b.HasIndex("MonitoredRepositoryId", "IssueNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_issues_monitored_repository_id_issue_number");

                    b.ToTable("issues", null, t =>
                        {
                            t.HasCheckConstraint("ck_issues_completed_completed_at", "state <> 'completed' OR completed_at IS NOT NULL");

                            t.HasCheckConstraint("ck_issues_continuable_failed_fields", "state <> 'continuable_failed' OR (worker_run_id IS NOT NULL AND branch_name IS NOT NULL AND failure_reason IS NOT NULL AND failed_at IS NOT NULL AND latest_progress IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_continuation_queued_branch_name", "state <> 'continuation_queued' OR branch_name IS NOT NULL");

                            t.HasCheckConstraint("ck_issues_dismissed_completed_at", "state <> 'dismissed' OR completed_at IS NOT NULL");

                            t.HasCheckConstraint("ck_issues_failed_fields", "state <> 'failed' OR (worker_run_id IS NOT NULL AND failure_reason IS NOT NULL AND failed_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_in_progress_worker_run_id", "state <> 'in_progress' OR worker_run_id IS NOT NULL");

                            t.HasCheckConstraint("ck_issues_ineligible_violations", "state <> 'ineligible' OR eligibility_violations IS NOT NULL");

                            t.HasCheckConstraint("ck_issues_review_fields", "state <> 'review' OR (worker_run_id IS NOT NULL AND branch_name IS NOT NULL AND pull_request_url IS NOT NULL AND feedback_cutoff_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_revision_failed_fields", "state <> 'revision_failed' OR (worker_run_id IS NOT NULL AND branch_name IS NOT NULL AND pull_request_url IS NOT NULL AND review_comments IS NOT NULL AND failure_reason IS NOT NULL AND failed_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_revision_in_progress_fields", "state <> 'revision_in_progress' OR (worker_run_id IS NOT NULL AND branch_name IS NOT NULL AND pull_request_url IS NOT NULL AND review_comments IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_revision_queued_fields", "state <> 'revision_queued' OR (branch_name IS NOT NULL AND pull_request_url IS NOT NULL AND review_comments IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_unchanged_worker_run_id", "state <> 'unchanged' OR worker_run_id IS NOT NULL");
                        });

                    b.HasDiscriminator<string>("state").IsComplete(true).HasValue("Issue");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Foundry.Modules.Monitoring.Domain.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("base_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("SecretKeyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("secret_key_name");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("accounts", (string)null);

                    b.HasDiscriminator<string>("type").IsComplete(true).HasValue("Account");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Foundry.Modules.Monitoring.Domain.Entities.MonitoredRepository", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT")
                        .HasColumnName("account_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LastPolledAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_polled_at");

                    b.Property<TimeSpan?>("PollInterval")
                        .HasColumnType("TEXT")
                        .HasColumnName("poll_interval");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("slug");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_monitored_repositories_account_id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_monitored_repositories_slug");

                    b.ToTable("monitored_repositories", (string)null);
                });

            modelBuilder.Entity("Foundry.Modules.Settings.Domain.GlobalSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AuthMode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("auth_mode");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("MaxConcurrent")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_concurrent");

                    b.Property<int>("TimeoutMinutes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("timeout_minutes");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("global_settings", (string)null);
                });

            modelBuilder.Entity("Foundry.Modules.Workers.Domain.WorkerReport", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("IngestedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("ingested_at");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("report_type");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sequence_number");

                    b.Property<Guid>("WorkerRunId")
                        .HasColumnType("TEXT")
                        .HasColumnName("worker_run_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkerRunId", "SequenceNumber")
                        .HasDatabaseName("ix_worker_reports_worker_run_id_sequence_number");

                    b.ToTable("worker_reports", (string)null);
                });

            modelBuilder.Entity("Foundry.Modules.Workers.Domain.WorkerRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<Guid>("IssueId")
                        .HasColumnType("TEXT")
                        .HasColumnName("issue_id");

                    b.Property<string>("state")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("state");

                    b.HasKey("Id");

                    b.HasIndex("IssueId")
                        .HasDatabaseName("ix_worker_runs_issue_id");

                    b.ToTable("worker_runs", null, t =>
                        {
                            t.HasCheckConstraint("ck_worker_runs_active_container_id", "state <> 'active' OR container_id IS NOT NULL");

                            t.HasCheckConstraint("ck_worker_runs_active_started_at", "state <> 'active' OR started_at IS NOT NULL");

                            t.HasCheckConstraint("ck_worker_runs_completed_completed_at", "state <> 'completed' OR completed_at IS NOT NULL");

                            t.HasCheckConstraint("ck_worker_runs_completed_exit_code", "state <> 'completed' OR exit_code IS NOT NULL");

                            t.HasCheckConstraint("ck_worker_runs_failed_failed_at", "state <> 'failed' OR failed_at IS NOT NULL");

                            t.HasCheckConstraint("ck_worker_runs_failed_reason", "state <> 'failed' OR reason IS NOT NULL");
                        });

                    b.HasDiscriminator<string>("state").IsComplete(true).HasValue("WorkerRun");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Foundry.Modules.Issues.Domain.BlockedIssue", b =>
                {
                    b.HasBaseType("Foundry.Modules.Issues.Domain.Issue");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("ck_issues_completed_completed_at", "state <> 'completed' OR completed_at IS NOT NULL");

                            t.HasCheckConstraint("ck_issues_continuable_failed_fields", "state <> 'continuable_failed' OR (worker_run_id IS NOT NULL AND branch_name IS NOT NULL AND failure_reason IS NOT NULL AND failed_at IS NOT NULL AND latest_progress IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_continuation_queued_branch_name", "state <> 'continuation_queued' OR branch_name IS NOT NULL");

                            t.HasCheckConstraint("ck_issues_dismissed_completed_at", "state <> 'dismissed' OR completed_at IS NOT NULL");

                            t.HasCheckConstraint("ck_issues_failed_fields", "state <> 'failed' OR (worker_run_id IS NOT NULL AND failure_reason IS NOT NULL AND failed_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_in_progress_worker_run_id", "state <> 'in_progress' OR worker_run_id IS NOT NULL");

                            t.HasCheckConstraint("ck_issues_ineligible_violations", "state <> 'ineligible' OR eligibility_violations IS NOT NULL");

                            t.HasCheckConstraint("ck_issues_review_fields", "state <> 'review' OR (worker_run_id IS NOT NULL AND branch_name IS NOT NULL AND pull_request_url IS NOT NULL AND feedback_cutoff_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_revision_failed_fields", "state <> 'revision_failed' OR (worker_run_id IS NOT NULL AND branch_name IS NOT NULL AND pull_request_url IS NOT NULL AND review_comments IS NOT NULL AND failure_reason IS NOT NULL AND failed_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_revision_in_progress_fields", "state <> 'revision_in_progress' OR (worker_run_id IS NOT NULL AND branch_name IS NOT NULL AND pull_request_url IS NOT NULL AND review_comments IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_revision_queued_fields", "state <> 'revision_queued' OR (branch_name IS NOT NULL AND pull_request_url IS NOT NULL AND review_comments IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_unchanged_worker_run_id", "state <> 'unchanged' OR worker_run_id IS NOT NULL");
                        });

                    b.HasDiscriminator().HasValue("blocked");
                });

            modelBuilder.Entity("Foundry.Modules.Issues.Domain.CompletedIssue", b =>
                {
                    b.HasBaseType("Foundry.Modules.Issues.Domain.Issue");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("branch_name");

                    b.Property<DateTimeOffset>("CompletedAt")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT")
                        .HasColumnName("completed_at");

                    b.Property<string>("PullRequestUrl")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(2000)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("pull_request_url");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("ck_issues_completed_completed_at", "state <> 'completed' OR completed_at IS NOT NULL");

                            t.HasCheckConstraint("ck_issues_continuable_failed_fields", "state <> 'continuable_failed' OR (worker_run_id IS NOT NULL AND branch_name IS NOT NULL AND failure_reason IS NOT NULL AND failed_at IS NOT NULL AND latest_progress IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_continuation_queued_branch_name", "state <> 'continuation_queued' OR branch_name IS NOT NULL");

                            t.HasCheckConstraint("ck_issues_dismissed_completed_at", "state <> 'dismissed' OR completed_at IS NOT NULL");

                            t.HasCheckConstraint("ck_issues_failed_fields", "state <> 'failed' OR (worker_run_id IS NOT NULL AND failure_reason IS NOT NULL AND failed_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_in_progress_worker_run_id", "state <> 'in_progress' OR worker_run_id IS NOT NULL");

                            t.HasCheckConstraint("ck_issues_ineligible_violations", "state <> 'ineligible' OR eligibility_violations IS NOT NULL");

                            t.HasCheckConstraint("ck_issues_review_fields", "state <> 'review' OR (worker_run_id IS NOT NULL AND branch_name IS NOT NULL AND pull_request_url IS NOT NULL AND feedback_cutoff_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_revision_failed_fields", "state <> 'revision_failed' OR (worker_run_id IS NOT NULL AND branch_name IS NOT NULL AND pull_request_url IS NOT NULL AND review_comments IS NOT NULL AND failure_reason IS NOT NULL AND failed_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_revision_in_progress_fields", "state <> 'revision_in_progress' OR (worker_run_id IS NOT NULL AND branch_name IS NOT NULL AND pull_request_url IS NOT NULL AND review_comments IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_revision_queued_fields", "state <> 'revision_queued' OR (branch_name IS NOT NULL AND pull_request_url IS NOT NULL AND review_comments IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_unchanged_worker_run_id", "state <> 'unchanged' OR worker_run_id IS NOT NULL");
                        });

                    b.HasDiscriminator().HasValue("completed");
                });

            modelBuilder.Entity("Foundry.Modules.Issues.Domain.ContinuableFailedIssue", b =>
                {
                    b.HasBaseType("Foundry.Modules.Issues.Domain.Issue");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("branch_name");

                    b.Property<DateTimeOffset>("FailedAt")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT")
                        .HasColumnName("failed_at");

                    b.Property<string>("FailureReason")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("failure_reason");

                    b.Property<string>("LatestProgress")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("latest_progress");

                    b.Property<string>("PullRequestUrl")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(2000)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("pull_request_url");

                    b.Property<Guid>("WorkerRunId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT")
                        .HasColumnName("worker_run_id");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("ck_issues_completed_completed_at", "state <> 'completed' OR completed_at IS NOT NULL");

                            t.HasCheckConstraint("ck_issues_continuable_failed_fields", "state <> 'continuable_failed' OR (worker_run_id IS NOT NULL AND branch_name IS NOT NULL AND failure_reason IS NOT NULL AND failed_at IS NOT NULL AND latest_progress IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_continuation_queued_branch_name", "state <> 'continuation_queued' OR branch_name IS NOT NULL");

                            t.HasCheckConstraint("ck_issues_dismissed_completed_at", "state <> 'dismissed' OR completed_at IS NOT NULL");

                            t.HasCheckConstraint("ck_issues_failed_fields", "state <> 'failed' OR (worker_run_id IS NOT NULL AND failure_reason IS NOT NULL AND failed_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_in_progress_worker_run_id", "state <> 'in_progress' OR worker_run_id IS NOT NULL");

                            t.HasCheckConstraint("ck_issues_ineligible_violations", "state <> 'ineligible' OR eligibility_violations IS NOT NULL");

                            t.HasCheckConstraint("ck_issues_review_fields", "state <> 'review' OR (worker_run_id IS NOT NULL AND branch_name IS NOT NULL AND pull_request_url IS NOT NULL AND feedback_cutoff_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_revision_failed_fields", "state <> 'revision_failed' OR (worker_run_id IS NOT NULL AND branch_name IS NOT NULL AND pull_request_url IS NOT NULL AND review_comments IS NOT NULL AND failure_reason IS NOT NULL AND failed_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_revision_in_progress_fields", "state <> 'revision_in_progress' OR (worker_run_id IS NOT NULL AND branch_name IS NOT NULL AND pull_request_url IS NOT NULL AND review_comments IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_revision_queued_fields", "state <> 'revision_queued' OR (branch_name IS NOT NULL AND pull_request_url IS NOT NULL AND review_comments IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_unchanged_worker_run_id", "state <> 'unchanged' OR worker_run_id IS NOT NULL");
                        });

                    b.HasDiscriminator().HasValue("continuable_failed");
                });

            modelBuilder.Entity("Foundry.Modules.Issues.Domain.ContinuationQueuedIssue", b =>
                {
                    b.HasBaseType("Foundry.Modules.Issues.Domain.Issue");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("branch_name");

                    b.Property<string>("LatestProgress")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("latest_progress");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("ck_issues_completed_completed_at", "state <> 'completed' OR completed_at IS NOT NULL");

                            t.HasCheckConstraint("ck_issues_continuable_failed_fields", "state <> 'continuable_failed' OR (worker_run_id IS NOT NULL AND branch_name IS NOT NULL AND failure_reason IS NOT NULL AND failed_at IS NOT NULL AND latest_progress IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_continuation_queued_branch_name", "state <> 'continuation_queued' OR branch_name IS NOT NULL");

                            t.HasCheckConstraint("ck_issues_dismissed_completed_at", "state <> 'dismissed' OR completed_at IS NOT NULL");

                            t.HasCheckConstraint("ck_issues_failed_fields", "state <> 'failed' OR (worker_run_id IS NOT NULL AND failure_reason IS NOT NULL AND failed_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_in_progress_worker_run_id", "state <> 'in_progress' OR worker_run_id IS NOT NULL");

                            t.HasCheckConstraint("ck_issues_ineligible_violations", "state <> 'ineligible' OR eligibility_violations IS NOT NULL");

                            t.HasCheckConstraint("ck_issues_review_fields", "state <> 'review' OR (worker_run_id IS NOT NULL AND branch_name IS NOT NULL AND pull_request_url IS NOT NULL AND feedback_cutoff_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_revision_failed_fields", "state <> 'revision_failed' OR (worker_run_id IS NOT NULL AND branch_name IS NOT NULL AND pull_request_url IS NOT NULL AND review_comments IS NOT NULL AND failure_reason IS NOT NULL AND failed_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_revision_in_progress_fields", "state <> 'revision_in_progress' OR (worker_run_id IS NOT NULL AND branch_name IS NOT NULL AND pull_request_url IS NOT NULL AND review_comments IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_revision_queued_fields", "state <> 'revision_queued' OR (branch_name IS NOT NULL AND pull_request_url IS NOT NULL AND review_comments IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_unchanged_worker_run_id", "state <> 'unchanged' OR worker_run_id IS NOT NULL");
                        });

                    b.HasDiscriminator().HasValue("continuation_queued");
                });

            modelBuilder.Entity("Foundry.Modules.Issues.Domain.DetectedIssue", b =>
                {
                    b.HasBaseType("Foundry.Modules.Issues.Domain.Issue");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("ck_issues_completed_completed_at", "state <> 'completed' OR completed_at IS NOT NULL");

                            t.HasCheckConstraint("ck_issues_continuable_failed_fields", "state <> 'continuable_failed' OR (worker_run_id IS NOT NULL AND branch_name IS NOT NULL AND failure_reason IS NOT NULL AND failed_at IS NOT NULL AND latest_progress IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_continuation_queued_branch_name", "state <> 'continuation_queued' OR branch_name IS NOT NULL");

                            t.HasCheckConstraint("ck_issues_dismissed_completed_at", "state <> 'dismissed' OR completed_at IS NOT NULL");

                            t.HasCheckConstraint("ck_issues_failed_fields", "state <> 'failed' OR (worker_run_id IS NOT NULL AND failure_reason IS NOT NULL AND failed_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_in_progress_worker_run_id", "state <> 'in_progress' OR worker_run_id IS NOT NULL");

                            t.HasCheckConstraint("ck_issues_ineligible_violations", "state <> 'ineligible' OR eligibility_violations IS NOT NULL");

                            t.HasCheckConstraint("ck_issues_review_fields", "state <> 'review' OR (worker_run_id IS NOT NULL AND branch_name IS NOT NULL AND pull_request_url IS NOT NULL AND feedback_cutoff_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_revision_failed_fields", "state <> 'revision_failed' OR (worker_run_id IS NOT NULL AND branch_name IS NOT NULL AND pull_request_url IS NOT NULL AND review_comments IS NOT NULL AND failure_reason IS NOT NULL AND failed_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_revision_in_progress_fields", "state <> 'revision_in_progress' OR (worker_run_id IS NOT NULL AND branch_name IS NOT NULL AND pull_request_url IS NOT NULL AND review_comments IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_revision_queued_fields", "state <> 'revision_queued' OR (branch_name IS NOT NULL AND pull_request_url IS NOT NULL AND review_comments IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_unchanged_worker_run_id", "state <> 'unchanged' OR worker_run_id IS NOT NULL");
                        });

                    b.HasDiscriminator().HasValue("detected");
                });

            modelBuilder.Entity("Foundry.Modules.Issues.Domain.DismissedIssue", b =>
                {
                    b.HasBaseType("Foundry.Modules.Issues.Domain.Issue");

                    b.Property<DateTimeOffset>("CompletedAt")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT")
                        .HasColumnName("completed_at");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("ck_issues_completed_completed_at", "state <> 'completed' OR completed_at IS NOT NULL");

                            t.HasCheckConstraint("ck_issues_continuable_failed_fields", "state <> 'continuable_failed' OR (worker_run_id IS NOT NULL AND branch_name IS NOT NULL AND failure_reason IS NOT NULL AND failed_at IS NOT NULL AND latest_progress IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_continuation_queued_branch_name", "state <> 'continuation_queued' OR branch_name IS NOT NULL");

                            t.HasCheckConstraint("ck_issues_dismissed_completed_at", "state <> 'dismissed' OR completed_at IS NOT NULL");

                            t.HasCheckConstraint("ck_issues_failed_fields", "state <> 'failed' OR (worker_run_id IS NOT NULL AND failure_reason IS NOT NULL AND failed_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_in_progress_worker_run_id", "state <> 'in_progress' OR worker_run_id IS NOT NULL");

                            t.HasCheckConstraint("ck_issues_ineligible_violations", "state <> 'ineligible' OR eligibility_violations IS NOT NULL");

                            t.HasCheckConstraint("ck_issues_review_fields", "state <> 'review' OR (worker_run_id IS NOT NULL AND branch_name IS NOT NULL AND pull_request_url IS NOT NULL AND feedback_cutoff_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_revision_failed_fields", "state <> 'revision_failed' OR (worker_run_id IS NOT NULL AND branch_name IS NOT NULL AND pull_request_url IS NOT NULL AND review_comments IS NOT NULL AND failure_reason IS NOT NULL AND failed_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_revision_in_progress_fields", "state <> 'revision_in_progress' OR (worker_run_id IS NOT NULL AND branch_name IS NOT NULL AND pull_request_url IS NOT NULL AND review_comments IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_revision_queued_fields", "state <> 'revision_queued' OR (branch_name IS NOT NULL AND pull_request_url IS NOT NULL AND review_comments IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_unchanged_worker_run_id", "state <> 'unchanged' OR worker_run_id IS NOT NULL");
                        });

                    b.HasDiscriminator().HasValue("dismissed");
                });

            modelBuilder.Entity("Foundry.Modules.Issues.Domain.FailedIssue", b =>
                {
                    b.HasBaseType("Foundry.Modules.Issues.Domain.Issue");

                    b.Property<DateTimeOffset>("FailedAt")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT")
                        .HasColumnName("failed_at");

                    b.Property<string>("FailureReason")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("failure_reason");

                    b.Property<Guid>("WorkerRunId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT")
                        .HasColumnName("worker_run_id");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("ck_issues_completed_completed_at", "state <> 'completed' OR completed_at IS NOT NULL");

                            t.HasCheckConstraint("ck_issues_continuable_failed_fields", "state <> 'continuable_failed' OR (worker_run_id IS NOT NULL AND branch_name IS NOT NULL AND failure_reason IS NOT NULL AND failed_at IS NOT NULL AND latest_progress IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_continuation_queued_branch_name", "state <> 'continuation_queued' OR branch_name IS NOT NULL");

                            t.HasCheckConstraint("ck_issues_dismissed_completed_at", "state <> 'dismissed' OR completed_at IS NOT NULL");

                            t.HasCheckConstraint("ck_issues_failed_fields", "state <> 'failed' OR (worker_run_id IS NOT NULL AND failure_reason IS NOT NULL AND failed_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_in_progress_worker_run_id", "state <> 'in_progress' OR worker_run_id IS NOT NULL");

                            t.HasCheckConstraint("ck_issues_ineligible_violations", "state <> 'ineligible' OR eligibility_violations IS NOT NULL");

                            t.HasCheckConstraint("ck_issues_review_fields", "state <> 'review' OR (worker_run_id IS NOT NULL AND branch_name IS NOT NULL AND pull_request_url IS NOT NULL AND feedback_cutoff_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_revision_failed_fields", "state <> 'revision_failed' OR (worker_run_id IS NOT NULL AND branch_name IS NOT NULL AND pull_request_url IS NOT NULL AND review_comments IS NOT NULL AND failure_reason IS NOT NULL AND failed_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_revision_in_progress_fields", "state <> 'revision_in_progress' OR (worker_run_id IS NOT NULL AND branch_name IS NOT NULL AND pull_request_url IS NOT NULL AND review_comments IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_revision_queued_fields", "state <> 'revision_queued' OR (branch_name IS NOT NULL AND pull_request_url IS NOT NULL AND review_comments IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_unchanged_worker_run_id", "state <> 'unchanged' OR worker_run_id IS NOT NULL");
                        });

                    b.HasDiscriminator().HasValue("failed");
                });

            modelBuilder.Entity("Foundry.Modules.Issues.Domain.InProgressIssue", b =>
                {
                    b.HasBaseType("Foundry.Modules.Issues.Domain.Issue");

                    b.Property<Guid>("WorkerRunId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT")
                        .HasColumnName("worker_run_id");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("ck_issues_completed_completed_at", "state <> 'completed' OR completed_at IS NOT NULL");

                            t.HasCheckConstraint("ck_issues_continuable_failed_fields", "state <> 'continuable_failed' OR (worker_run_id IS NOT NULL AND branch_name IS NOT NULL AND failure_reason IS NOT NULL AND failed_at IS NOT NULL AND latest_progress IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_continuation_queued_branch_name", "state <> 'continuation_queued' OR branch_name IS NOT NULL");

                            t.HasCheckConstraint("ck_issues_dismissed_completed_at", "state <> 'dismissed' OR completed_at IS NOT NULL");

                            t.HasCheckConstraint("ck_issues_failed_fields", "state <> 'failed' OR (worker_run_id IS NOT NULL AND failure_reason IS NOT NULL AND failed_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_in_progress_worker_run_id", "state <> 'in_progress' OR worker_run_id IS NOT NULL");

                            t.HasCheckConstraint("ck_issues_ineligible_violations", "state <> 'ineligible' OR eligibility_violations IS NOT NULL");

                            t.HasCheckConstraint("ck_issues_review_fields", "state <> 'review' OR (worker_run_id IS NOT NULL AND branch_name IS NOT NULL AND pull_request_url IS NOT NULL AND feedback_cutoff_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_revision_failed_fields", "state <> 'revision_failed' OR (worker_run_id IS NOT NULL AND branch_name IS NOT NULL AND pull_request_url IS NOT NULL AND review_comments IS NOT NULL AND failure_reason IS NOT NULL AND failed_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_revision_in_progress_fields", "state <> 'revision_in_progress' OR (worker_run_id IS NOT NULL AND branch_name IS NOT NULL AND pull_request_url IS NOT NULL AND review_comments IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_revision_queued_fields", "state <> 'revision_queued' OR (branch_name IS NOT NULL AND pull_request_url IS NOT NULL AND review_comments IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_unchanged_worker_run_id", "state <> 'unchanged' OR worker_run_id IS NOT NULL");
                        });

                    b.HasDiscriminator().HasValue("in_progress");
                });

            modelBuilder.Entity("Foundry.Modules.Issues.Domain.IneligibleIssue", b =>
                {
                    b.HasBaseType("Foundry.Modules.Issues.Domain.Issue");

                    b.Property<string>("Violations")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("eligibility_violations");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("ck_issues_completed_completed_at", "state <> 'completed' OR completed_at IS NOT NULL");

                            t.HasCheckConstraint("ck_issues_continuable_failed_fields", "state <> 'continuable_failed' OR (worker_run_id IS NOT NULL AND branch_name IS NOT NULL AND failure_reason IS NOT NULL AND failed_at IS NOT NULL AND latest_progress IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_continuation_queued_branch_name", "state <> 'continuation_queued' OR branch_name IS NOT NULL");

                            t.HasCheckConstraint("ck_issues_dismissed_completed_at", "state <> 'dismissed' OR completed_at IS NOT NULL");

                            t.HasCheckConstraint("ck_issues_failed_fields", "state <> 'failed' OR (worker_run_id IS NOT NULL AND failure_reason IS NOT NULL AND failed_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_in_progress_worker_run_id", "state <> 'in_progress' OR worker_run_id IS NOT NULL");

                            t.HasCheckConstraint("ck_issues_ineligible_violations", "state <> 'ineligible' OR eligibility_violations IS NOT NULL");

                            t.HasCheckConstraint("ck_issues_review_fields", "state <> 'review' OR (worker_run_id IS NOT NULL AND branch_name IS NOT NULL AND pull_request_url IS NOT NULL AND feedback_cutoff_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_revision_failed_fields", "state <> 'revision_failed' OR (worker_run_id IS NOT NULL AND branch_name IS NOT NULL AND pull_request_url IS NOT NULL AND review_comments IS NOT NULL AND failure_reason IS NOT NULL AND failed_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_revision_in_progress_fields", "state <> 'revision_in_progress' OR (worker_run_id IS NOT NULL AND branch_name IS NOT NULL AND pull_request_url IS NOT NULL AND review_comments IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_revision_queued_fields", "state <> 'revision_queued' OR (branch_name IS NOT NULL AND pull_request_url IS NOT NULL AND review_comments IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_unchanged_worker_run_id", "state <> 'unchanged' OR worker_run_id IS NOT NULL");
                        });

                    b.HasDiscriminator().HasValue("ineligible");
                });

            modelBuilder.Entity("Foundry.Modules.Issues.Domain.QueuedIssue", b =>
                {
                    b.HasBaseType("Foundry.Modules.Issues.Domain.Issue");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("ck_issues_completed_completed_at", "state <> 'completed' OR completed_at IS NOT NULL");

                            t.HasCheckConstraint("ck_issues_continuable_failed_fields", "state <> 'continuable_failed' OR (worker_run_id IS NOT NULL AND branch_name IS NOT NULL AND failure_reason IS NOT NULL AND failed_at IS NOT NULL AND latest_progress IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_continuation_queued_branch_name", "state <> 'continuation_queued' OR branch_name IS NOT NULL");

                            t.HasCheckConstraint("ck_issues_dismissed_completed_at", "state <> 'dismissed' OR completed_at IS NOT NULL");

                            t.HasCheckConstraint("ck_issues_failed_fields", "state <> 'failed' OR (worker_run_id IS NOT NULL AND failure_reason IS NOT NULL AND failed_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_in_progress_worker_run_id", "state <> 'in_progress' OR worker_run_id IS NOT NULL");

                            t.HasCheckConstraint("ck_issues_ineligible_violations", "state <> 'ineligible' OR eligibility_violations IS NOT NULL");

                            t.HasCheckConstraint("ck_issues_review_fields", "state <> 'review' OR (worker_run_id IS NOT NULL AND branch_name IS NOT NULL AND pull_request_url IS NOT NULL AND feedback_cutoff_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_revision_failed_fields", "state <> 'revision_failed' OR (worker_run_id IS NOT NULL AND branch_name IS NOT NULL AND pull_request_url IS NOT NULL AND review_comments IS NOT NULL AND failure_reason IS NOT NULL AND failed_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_revision_in_progress_fields", "state <> 'revision_in_progress' OR (worker_run_id IS NOT NULL AND branch_name IS NOT NULL AND pull_request_url IS NOT NULL AND review_comments IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_revision_queued_fields", "state <> 'revision_queued' OR (branch_name IS NOT NULL AND pull_request_url IS NOT NULL AND review_comments IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_unchanged_worker_run_id", "state <> 'unchanged' OR worker_run_id IS NOT NULL");
                        });

                    b.HasDiscriminator().HasValue("queued");
                });

            modelBuilder.Entity("Foundry.Modules.Issues.Domain.ReviewIssue", b =>
                {
                    b.HasBaseType("Foundry.Modules.Issues.Domain.Issue");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("branch_name");

                    b.Property<DateTimeOffset>("FeedbackCutoffAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("feedback_cutoff_at");

                    b.Property<string>("PullRequestUrl")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(2000)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("pull_request_url");

                    b.Property<Guid>("WorkerRunId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT")
                        .HasColumnName("worker_run_id");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("ck_issues_completed_completed_at", "state <> 'completed' OR completed_at IS NOT NULL");

                            t.HasCheckConstraint("ck_issues_continuable_failed_fields", "state <> 'continuable_failed' OR (worker_run_id IS NOT NULL AND branch_name IS NOT NULL AND failure_reason IS NOT NULL AND failed_at IS NOT NULL AND latest_progress IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_continuation_queued_branch_name", "state <> 'continuation_queued' OR branch_name IS NOT NULL");

                            t.HasCheckConstraint("ck_issues_dismissed_completed_at", "state <> 'dismissed' OR completed_at IS NOT NULL");

                            t.HasCheckConstraint("ck_issues_failed_fields", "state <> 'failed' OR (worker_run_id IS NOT NULL AND failure_reason IS NOT NULL AND failed_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_in_progress_worker_run_id", "state <> 'in_progress' OR worker_run_id IS NOT NULL");

                            t.HasCheckConstraint("ck_issues_ineligible_violations", "state <> 'ineligible' OR eligibility_violations IS NOT NULL");

                            t.HasCheckConstraint("ck_issues_review_fields", "state <> 'review' OR (worker_run_id IS NOT NULL AND branch_name IS NOT NULL AND pull_request_url IS NOT NULL AND feedback_cutoff_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_revision_failed_fields", "state <> 'revision_failed' OR (worker_run_id IS NOT NULL AND branch_name IS NOT NULL AND pull_request_url IS NOT NULL AND review_comments IS NOT NULL AND failure_reason IS NOT NULL AND failed_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_revision_in_progress_fields", "state <> 'revision_in_progress' OR (worker_run_id IS NOT NULL AND branch_name IS NOT NULL AND pull_request_url IS NOT NULL AND review_comments IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_revision_queued_fields", "state <> 'revision_queued' OR (branch_name IS NOT NULL AND pull_request_url IS NOT NULL AND review_comments IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_unchanged_worker_run_id", "state <> 'unchanged' OR worker_run_id IS NOT NULL");
                        });

                    b.HasDiscriminator().HasValue("review");
                });

            modelBuilder.Entity("Foundry.Modules.Issues.Domain.RevisionFailedIssue", b =>
                {
                    b.HasBaseType("Foundry.Modules.Issues.Domain.Issue");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("branch_name");

                    b.Property<DateTimeOffset>("FailedAt")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT")
                        .HasColumnName("failed_at");

                    b.Property<string>("FailureReason")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("failure_reason");

                    b.Property<string>("PullRequestUrl")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(2000)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("pull_request_url");

                    b.Property<string>("ReviewComments")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(2147483647)
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .HasColumnName("review_comments");

                    b.Property<Guid>("WorkerRunId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT")
                        .HasColumnName("worker_run_id");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("ck_issues_completed_completed_at", "state <> 'completed' OR completed_at IS NOT NULL");

                            t.HasCheckConstraint("ck_issues_continuable_failed_fields", "state <> 'continuable_failed' OR (worker_run_id IS NOT NULL AND branch_name IS NOT NULL AND failure_reason IS NOT NULL AND failed_at IS NOT NULL AND latest_progress IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_continuation_queued_branch_name", "state <> 'continuation_queued' OR branch_name IS NOT NULL");

                            t.HasCheckConstraint("ck_issues_dismissed_completed_at", "state <> 'dismissed' OR completed_at IS NOT NULL");

                            t.HasCheckConstraint("ck_issues_failed_fields", "state <> 'failed' OR (worker_run_id IS NOT NULL AND failure_reason IS NOT NULL AND failed_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_in_progress_worker_run_id", "state <> 'in_progress' OR worker_run_id IS NOT NULL");

                            t.HasCheckConstraint("ck_issues_ineligible_violations", "state <> 'ineligible' OR eligibility_violations IS NOT NULL");

                            t.HasCheckConstraint("ck_issues_review_fields", "state <> 'review' OR (worker_run_id IS NOT NULL AND branch_name IS NOT NULL AND pull_request_url IS NOT NULL AND feedback_cutoff_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_revision_failed_fields", "state <> 'revision_failed' OR (worker_run_id IS NOT NULL AND branch_name IS NOT NULL AND pull_request_url IS NOT NULL AND review_comments IS NOT NULL AND failure_reason IS NOT NULL AND failed_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_revision_in_progress_fields", "state <> 'revision_in_progress' OR (worker_run_id IS NOT NULL AND branch_name IS NOT NULL AND pull_request_url IS NOT NULL AND review_comments IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_revision_queued_fields", "state <> 'revision_queued' OR (branch_name IS NOT NULL AND pull_request_url IS NOT NULL AND review_comments IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_unchanged_worker_run_id", "state <> 'unchanged' OR worker_run_id IS NOT NULL");
                        });

                    b.HasDiscriminator().HasValue("revision_failed");
                });

            modelBuilder.Entity("Foundry.Modules.Issues.Domain.RevisionInProgressIssue", b =>
                {
                    b.HasBaseType("Foundry.Modules.Issues.Domain.Issue");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("branch_name");

                    b.Property<string>("PullRequestUrl")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(2000)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("pull_request_url");

                    b.Property<string>("ReviewComments")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(2147483647)
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .HasColumnName("review_comments");

                    b.Property<Guid>("WorkerRunId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT")
                        .HasColumnName("worker_run_id");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("ck_issues_completed_completed_at", "state <> 'completed' OR completed_at IS NOT NULL");

                            t.HasCheckConstraint("ck_issues_continuable_failed_fields", "state <> 'continuable_failed' OR (worker_run_id IS NOT NULL AND branch_name IS NOT NULL AND failure_reason IS NOT NULL AND failed_at IS NOT NULL AND latest_progress IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_continuation_queued_branch_name", "state <> 'continuation_queued' OR branch_name IS NOT NULL");

                            t.HasCheckConstraint("ck_issues_dismissed_completed_at", "state <> 'dismissed' OR completed_at IS NOT NULL");

                            t.HasCheckConstraint("ck_issues_failed_fields", "state <> 'failed' OR (worker_run_id IS NOT NULL AND failure_reason IS NOT NULL AND failed_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_in_progress_worker_run_id", "state <> 'in_progress' OR worker_run_id IS NOT NULL");

                            t.HasCheckConstraint("ck_issues_ineligible_violations", "state <> 'ineligible' OR eligibility_violations IS NOT NULL");

                            t.HasCheckConstraint("ck_issues_review_fields", "state <> 'review' OR (worker_run_id IS NOT NULL AND branch_name IS NOT NULL AND pull_request_url IS NOT NULL AND feedback_cutoff_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_revision_failed_fields", "state <> 'revision_failed' OR (worker_run_id IS NOT NULL AND branch_name IS NOT NULL AND pull_request_url IS NOT NULL AND review_comments IS NOT NULL AND failure_reason IS NOT NULL AND failed_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_revision_in_progress_fields", "state <> 'revision_in_progress' OR (worker_run_id IS NOT NULL AND branch_name IS NOT NULL AND pull_request_url IS NOT NULL AND review_comments IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_revision_queued_fields", "state <> 'revision_queued' OR (branch_name IS NOT NULL AND pull_request_url IS NOT NULL AND review_comments IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_unchanged_worker_run_id", "state <> 'unchanged' OR worker_run_id IS NOT NULL");
                        });

                    b.HasDiscriminator().HasValue("revision_in_progress");
                });

            modelBuilder.Entity("Foundry.Modules.Issues.Domain.RevisionQueuedIssue", b =>
                {
                    b.HasBaseType("Foundry.Modules.Issues.Domain.Issue");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("branch_name");

                    b.Property<string>("PullRequestUrl")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(2000)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("pull_request_url");

                    b.Property<string>("ReviewComments")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(2147483647)
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .HasColumnName("review_comments");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("ck_issues_completed_completed_at", "state <> 'completed' OR completed_at IS NOT NULL");

                            t.HasCheckConstraint("ck_issues_continuable_failed_fields", "state <> 'continuable_failed' OR (worker_run_id IS NOT NULL AND branch_name IS NOT NULL AND failure_reason IS NOT NULL AND failed_at IS NOT NULL AND latest_progress IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_continuation_queued_branch_name", "state <> 'continuation_queued' OR branch_name IS NOT NULL");

                            t.HasCheckConstraint("ck_issues_dismissed_completed_at", "state <> 'dismissed' OR completed_at IS NOT NULL");

                            t.HasCheckConstraint("ck_issues_failed_fields", "state <> 'failed' OR (worker_run_id IS NOT NULL AND failure_reason IS NOT NULL AND failed_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_in_progress_worker_run_id", "state <> 'in_progress' OR worker_run_id IS NOT NULL");

                            t.HasCheckConstraint("ck_issues_ineligible_violations", "state <> 'ineligible' OR eligibility_violations IS NOT NULL");

                            t.HasCheckConstraint("ck_issues_review_fields", "state <> 'review' OR (worker_run_id IS NOT NULL AND branch_name IS NOT NULL AND pull_request_url IS NOT NULL AND feedback_cutoff_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_revision_failed_fields", "state <> 'revision_failed' OR (worker_run_id IS NOT NULL AND branch_name IS NOT NULL AND pull_request_url IS NOT NULL AND review_comments IS NOT NULL AND failure_reason IS NOT NULL AND failed_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_revision_in_progress_fields", "state <> 'revision_in_progress' OR (worker_run_id IS NOT NULL AND branch_name IS NOT NULL AND pull_request_url IS NOT NULL AND review_comments IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_revision_queued_fields", "state <> 'revision_queued' OR (branch_name IS NOT NULL AND pull_request_url IS NOT NULL AND review_comments IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_unchanged_worker_run_id", "state <> 'unchanged' OR worker_run_id IS NOT NULL");
                        });

                    b.HasDiscriminator().HasValue("revision_queued");
                });

            modelBuilder.Entity("Foundry.Modules.Issues.Domain.UnchangedIssue", b =>
                {
                    b.HasBaseType("Foundry.Modules.Issues.Domain.Issue");

                    b.Property<Guid>("WorkerRunId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT")
                        .HasColumnName("worker_run_id");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("ck_issues_completed_completed_at", "state <> 'completed' OR completed_at IS NOT NULL");

                            t.HasCheckConstraint("ck_issues_continuable_failed_fields", "state <> 'continuable_failed' OR (worker_run_id IS NOT NULL AND branch_name IS NOT NULL AND failure_reason IS NOT NULL AND failed_at IS NOT NULL AND latest_progress IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_continuation_queued_branch_name", "state <> 'continuation_queued' OR branch_name IS NOT NULL");

                            t.HasCheckConstraint("ck_issues_dismissed_completed_at", "state <> 'dismissed' OR completed_at IS NOT NULL");

                            t.HasCheckConstraint("ck_issues_failed_fields", "state <> 'failed' OR (worker_run_id IS NOT NULL AND failure_reason IS NOT NULL AND failed_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_in_progress_worker_run_id", "state <> 'in_progress' OR worker_run_id IS NOT NULL");

                            t.HasCheckConstraint("ck_issues_ineligible_violations", "state <> 'ineligible' OR eligibility_violations IS NOT NULL");

                            t.HasCheckConstraint("ck_issues_review_fields", "state <> 'review' OR (worker_run_id IS NOT NULL AND branch_name IS NOT NULL AND pull_request_url IS NOT NULL AND feedback_cutoff_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_revision_failed_fields", "state <> 'revision_failed' OR (worker_run_id IS NOT NULL AND branch_name IS NOT NULL AND pull_request_url IS NOT NULL AND review_comments IS NOT NULL AND failure_reason IS NOT NULL AND failed_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_revision_in_progress_fields", "state <> 'revision_in_progress' OR (worker_run_id IS NOT NULL AND branch_name IS NOT NULL AND pull_request_url IS NOT NULL AND review_comments IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_revision_queued_fields", "state <> 'revision_queued' OR (branch_name IS NOT NULL AND pull_request_url IS NOT NULL AND review_comments IS NOT NULL)");

                            t.HasCheckConstraint("ck_issues_unchanged_worker_run_id", "state <> 'unchanged' OR worker_run_id IS NOT NULL");
                        });

                    b.HasDiscriminator().HasValue("unchanged");
                });

            modelBuilder.Entity("Foundry.Modules.Monitoring.Domain.Entities.GitHubAccount", b =>
                {
                    b.HasBaseType("Foundry.Modules.Monitoring.Domain.Entities.Account");

                    b.HasDiscriminator().HasValue("github");
                });

            modelBuilder.Entity("Foundry.Modules.Workers.Domain.ActiveRun", b =>
                {
                    b.HasBaseType("Foundry.Modules.Workers.Domain.WorkerRun");

                    b.Property<string>("BranchName")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("branch_name");

                    b.Property<string>("ContainerId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("container_id");

                    b.Property<string>("LatestProgress")
                        .HasMaxLength(2147483647)
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .HasColumnName("latest_progress");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("ck_worker_runs_active_container_id", "state <> 'active' OR container_id IS NOT NULL");

                            t.HasCheckConstraint("ck_worker_runs_active_started_at", "state <> 'active' OR started_at IS NOT NULL");

                            t.HasCheckConstraint("ck_worker_runs_completed_completed_at", "state <> 'completed' OR completed_at IS NOT NULL");

                            t.HasCheckConstraint("ck_worker_runs_completed_exit_code", "state <> 'completed' OR exit_code IS NOT NULL");

                            t.HasCheckConstraint("ck_worker_runs_failed_failed_at", "state <> 'failed' OR failed_at IS NOT NULL");

                            t.HasCheckConstraint("ck_worker_runs_failed_reason", "state <> 'failed' OR reason IS NOT NULL");
                        });

                    b.HasDiscriminator().HasValue("active");
                });

            modelBuilder.Entity("Foundry.Modules.Workers.Domain.CompletedRun", b =>
                {
                    b.HasBaseType("Foundry.Modules.Workers.Domain.WorkerRun");

                    b.Property<string>("BranchName")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("branch_name");

                    b.Property<DateTimeOffset>("CompletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("completed_at");

                    b.Property<int>("ExitCode")
                        .HasColumnType("INTEGER")
                        .HasColumnName("exit_code");

                    b.Property<string>("PullRequestUrl")
                        .HasMaxLength(2000)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("pull_request_url");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("ck_worker_runs_active_container_id", "state <> 'active' OR container_id IS NOT NULL");

                            t.HasCheckConstraint("ck_worker_runs_active_started_at", "state <> 'active' OR started_at IS NOT NULL");

                            t.HasCheckConstraint("ck_worker_runs_completed_completed_at", "state <> 'completed' OR completed_at IS NOT NULL");

                            t.HasCheckConstraint("ck_worker_runs_completed_exit_code", "state <> 'completed' OR exit_code IS NOT NULL");

                            t.HasCheckConstraint("ck_worker_runs_failed_failed_at", "state <> 'failed' OR failed_at IS NOT NULL");

                            t.HasCheckConstraint("ck_worker_runs_failed_reason", "state <> 'failed' OR reason IS NOT NULL");
                        });

                    b.HasDiscriminator().HasValue("completed");
                });

            modelBuilder.Entity("Foundry.Modules.Workers.Domain.FailedRun", b =>
                {
                    b.HasBaseType("Foundry.Modules.Workers.Domain.WorkerRun");

                    b.Property<string>("BranchName")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("branch_name");

                    b.Property<string>("ContainerOutput")
                        .HasMaxLength(2147483647)
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .HasColumnName("container_output");

                    b.Property<DateTimeOffset>("FailedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("failed_at");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .HasColumnType("TEXT")
                        .HasColumnName("reason");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("ck_worker_runs_active_container_id", "state <> 'active' OR container_id IS NOT NULL");

                            t.HasCheckConstraint("ck_worker_runs_active_started_at", "state <> 'active' OR started_at IS NOT NULL");

                            t.HasCheckConstraint("ck_worker_runs_completed_completed_at", "state <> 'completed' OR completed_at IS NOT NULL");

                            t.HasCheckConstraint("ck_worker_runs_completed_exit_code", "state <> 'completed' OR exit_code IS NOT NULL");

                            t.HasCheckConstraint("ck_worker_runs_failed_failed_at", "state <> 'failed' OR failed_at IS NOT NULL");

                            t.HasCheckConstraint("ck_worker_runs_failed_reason", "state <> 'failed' OR reason IS NOT NULL");
                        });

                    b.HasDiscriminator().HasValue("failed");
                });

            modelBuilder.Entity("Foundry.Modules.Workers.Domain.StartingRun", b =>
                {
                    b.HasBaseType("Foundry.Modules.Workers.Domain.WorkerRun");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("ck_worker_runs_active_container_id", "state <> 'active' OR container_id IS NOT NULL");

                            t.HasCheckConstraint("ck_worker_runs_active_started_at", "state <> 'active' OR started_at IS NOT NULL");

                            t.HasCheckConstraint("ck_worker_runs_completed_completed_at", "state <> 'completed' OR completed_at IS NOT NULL");

                            t.HasCheckConstraint("ck_worker_runs_completed_exit_code", "state <> 'completed' OR exit_code IS NOT NULL");

                            t.HasCheckConstraint("ck_worker_runs_failed_failed_at", "state <> 'failed' OR failed_at IS NOT NULL");

                            t.HasCheckConstraint("ck_worker_runs_failed_reason", "state <> 'failed' OR reason IS NOT NULL");
                        });

                    b.HasDiscriminator().HasValue("starting");
                });

            modelBuilder.Entity("Foundry.Modules.Monitoring.Domain.Entities.MonitoredRepository", b =>
                {
                    b.HasOne("Foundry.Modules.Monitoring.Domain.Entities.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Foundry.Modules.Workers.Domain.WorkerReport", b =>
                {
                    b.HasOne("Foundry.Modules.Workers.Domain.WorkerRun", null)
                        .WithMany()
                        .HasForeignKey("WorkerRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
