namespace Foundry.Modules.Settings.Contracts;

public sealed record GlobalSettingsSummary(
    string AuthMode,
    int MaxConcurrent,
    int TimeoutMinutes,
    string OAuthStatus,
    DateTimeOffset? ExpiresAt,
    string? SubscriptionType,
    string? OAuthAccountEmail,
    string? OAuthAccountOrgName,
    string? SystemPromptTemplate,
    string? WorkerPromptTemplate,
    DateTimeOffset? UsageLimitResetsAt,
    bool IsDispatchPaused,
    bool AutoResumeOnUsageReset,
    int DefaultCooldownMinutes,
    bool InstallDotnet,
    bool InstallAngular,
    bool InstallGlab,
    bool InstallGh,
    bool InstallChromium,
    bool InstallDocker,
    ImageBuildStatus ImageBuildStatus,
    string? LastImageBuildError,
    bool HasUsableImage);
